"""sync_models_updated_at

Revision ID: caf1d78b4c80
Revises: 20250520_fix_updated_at
Create Date: 2025-04-15 02:35:29.697607+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'caf1d78b4c80'
down_revision = '20250520_fix_updated_at'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('clicks', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('clicks', 'user_agent',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('clicks', 'referrer',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('clicks', 'country',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('clicks', 'browser',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('clicks', 'os',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_clicks_link_id'), 'clicks', ['link_id'], unique=False)
    op.drop_constraint('clicks_link_id_fkey', 'clicks', type_='foreignkey')
    op.create_foreign_key(None, 'clicks', 'links', ['link_id'], ['id'], ondelete='CASCADE')
    op.drop_column('clicks', 'click_metadata')
    op.alter_column('links', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('links', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('links', 'click_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('links', 'is_password_protected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('links', 'link_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint('links_user_id_fkey', 'links', type_='foreignkey')
    op.create_foreign_key(None, 'links', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.create_foreign_key('links_user_id_fkey', 'links', 'users', ['user_id'], ['id'])
    op.alter_column('links', 'link_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('links', 'is_password_protected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('links', 'click_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('links', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('links', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.add_column('clicks', sa.Column('click_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'clicks', type_='foreignkey')
    op.create_foreign_key('clicks_link_id_fkey', 'clicks', 'links', ['link_id'], ['id'])
    op.drop_index(op.f('ix_clicks_link_id'), table_name='clicks')
    op.alter_column('clicks', 'os',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('clicks', 'browser',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('clicks', 'country',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
    op.alter_column('clicks', 'referrer',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('clicks', 'user_agent',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('clicks', 'ip_address',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)
    op.drop_column('clicks', 'created_at')
    # ### end Alembic commands ### 